name: DartWebGLEditor
description: WebGL
version: 0.0.1
dependencies:
  buckshot:
    git:
      url: git://github.com/prujohn/Buckshot.git
      ref: latest
  spectre:
    git: https://github.com/johnmccutchan/spectre.git